### ISSUE TITLE
Object of class DateTime could not be converted to string.

### ISSUE THREAD

**Issue by ben-callaway** [ethercreative/out#2]
When creating a single text field export, the error message displayed "Object of class DateTime could not be converted to string."

Could not get the plugin to work?

**Comment by alexjcollins** [comment]
@ben-callaway There is a known issue on v3 for this which we'll be fixing, soon hopefully. Are you able to export without putting date parameters on it for now?

**Comment by ben-callaway** [comment]
Not working for me unfortunately, with or without date criteria.
