### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by bdmtra** [ethercreative/out#3]
Get "Array to string conversion" while try to create new export

**Comment by alexjcollins** [comment]
@twopizza Could you let me know the different field types you have in the export (i.e. `Plain Text`, `Number`, `Entry` etc)? 

It may be that you're trying to export data from an unsupported third-party field type.

**Comment by bdmtra** [comment]
@alexjcollins it happens with any settings. Even with default https://gyazo.com/59adf0e25104a55e4bdc9308e37d75b5

**Comment by Tam** [comment]
@twopizza Can you share the stacktrace from the error?
