### ISSUE TITLE
Export fields reordering doesn't work

### ISSUE THREAD

**Issue by Stalex89** [ethercreative/out#5]
### Description

When trying to reorder the fields in export edit page and saving the changes, it doesn't save the new field order

### Steps to reproduce
1.Create new craft project
2.Install out plugin
3. Create a new export
4. Go to edit page, add fields, save the export
5. Go to edit page again, reorder the fields and save again

### Additional info
- Craft version: 3.4.17.1
- PHP version: 7.3.12
- Database driver & version: MySQL 5.7.28
- Plugins & versions: ethercreative/out "^3.0.5"

**Comment by Tam** [comment]
It seems to be working fine for me, perhaps something in the latest release fixed it. Do you still get the issue with the latest version? If you do, what other plugins do you have installed?

**Comment by Stalex89** [comment]
Looks like it was fixed with the latest release, thank you!
