### ISSUE TITLE
"Export..." button doesn't work

### ISSUE THREAD

**Issue by Stalex89** [ethercreative/out#7]
### Description

Plugin returns an error while pressing the "Export..." button on the plugin main page and does nothing

`
Uncaught This view is not selectable.
getSelectedElements @ Craft.min.js?v=1586347086:1
getSelectedElementIds @ Craft.min.js?v=1586347086:1
_showExportHud @ Craft.min.js?v=1586347086:1
(anonymous) @ garnish.js?v=1586347086:1
i @ jquery.js?v=1586347086:1
dispatch @ jquery.js?v=1586347086:1
v.handle @ jquery.js?v=1586347086:1
`

### Steps to reproduce
1. Create new craft project
2. Install out plugin
3. Create a new export
4. Go to main plugin page and press "Export..."
5. Look to the developer console for an error

### Additional info
- Craft version: 3.4.17.1
- PHP version: 7.3.12
- Database driver & version: MySQL 5.7.28
- Plugins & versions: ethercreative/out "^3.0.5"

**Comment by Tam** [comment]
I'm not seeing any errors, perhaps this was fixed in the latest release?

**Comment by Stalex89** [comment]
the plugin was tested on clear craft installation.
Added the repository with the issue, including fixes made a moment ago:

https://github.com/Stalex89/craft-out-export-issue.git

Database is included in a zip file with name "test_200501_124325_4sf59hds1n_v3.4.17.1.zip"
admin account: login - admin, pass - test123

![Screenshot 2020-05-01 at 14 50 38](https://user-images.githubusercontent.com/23526237/80806506-2c80b880-8bbb-11ea-960d-48cdf892f420.png)

Tested on different browsers, still get the same error

A little bit off question, but is there also a button to delete the export ? I can't find one

**Comment by Tam** [comment]
Ah, I see. I didn't realize you meant Craft's export button. That won't do anything since you can't export the Out exports. To download the export you have to click on the blue arrow in the download column.
For clarity I've removed that button in the latest release.
